# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI Notebooks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          python -m pip install .[lola,ci]
      - name: Test Tutorial_Basics_How_to_use_the_toolbox
        run: |
          jupyter nbconvert ./marltoolbox/examples/Tutorial_Basics_How_to_use_the_toolbox.ipynb --to script
          python ./marltoolbox/examples/Tutorial_Basics_How_to_use_the_toolbox.py
      - name: Test Tutorial_Evaluations_Level_1_best_response_and_self_play_and_cross_play
        run: |
          jupyter nbconvert ./marltoolbox/examples/Tutorial_Evaluations_Level_1_best_response_and_self_play_and_cross_play.ipynb --to script
          python ./marltoolbox/examples/Tutorial_Evaluations_Level_1_best_response_and_self_play_and_cross_play.py